steps:

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.0.100
    inputs:
      packageType: sdk
      version: 3.0.100

  - script: $(Build.Repository.LocalPath)/Scripts/Mac/NukeBuildOutputs.sh
    displayName: Delete previous build outputs
    continueOnError: true
      
  - task: InstallAppleCertificate@2
    displayName: 'Install Apple certificate'
    inputs:	
      certSecureFile: 'PrjFSKextCertExpiresJun6_2020_v2.p12'
      certPwd: '$(kext.certificate.password)'

  - script: Scripts/Mac/BuildScalarForMac.sh $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Build Scalar ($(configuration))

  - script: Scripts/Mac/RunUnitTests.sh $(configuration) $(Common.TestResultsDirectory)
    displayName: Run unit tests ($(configuration))

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: Mac $(configuration) Unit Tests
      publishRunAttachments: true
    condition: succeededOrFailed()

  - script: Scripts/Mac/CI/CreateFTDrop.sh $(configuration) $(Build.ArtifactStagingDirectory)/Tests
    displayName: Create functional tests drop

  - task: PublishBuildArtifacts@1
    displayName: Publish functional tests drop
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/Tests
      artifactName: "FunctionalTests_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))

  - script: Scripts/Mac/CI/CreateInstallerDrop.sh $(configuration) $(Build.ArtifactStagingDirectory)/Installers
    displayName: Create installers drop

  - task: PublishBuildArtifacts@1
    displayName: Publish installers drop
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/Installers
      artifactName: "Installers_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))
