steps:

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.0.100
    inputs:
      packageType: sdk
      version: 3.0.100

  - script: $(Build.Repository.LocalPath)\\Scripts\\NukeBuildOutputs.bat
    displayName: Delete previous build outputs
    continueOnError: true

  - powershell: |
      & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe' -Vr *,31bf3856ad364e35
      & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe' -Vr *,31bf3856ad364e35
    displayName: Disable strong name validation for MS delay-signed assemblies

  - script: $(Build.Repository.LocalPath)\Scripts\BuildScalarForWindows.bat $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Build Scalar ($(configuration))

  - script: $(Build.Repository.LocalPath)\Scripts\RunUnitTests.bat $(configuration) $(Common.TestResultsDirectory)
    displayName: Run unit tests ($(configuration))

  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testRunner: VSTest
      testResultsFiles: "**\\*.trx"
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: Windows $(configuration) Unit Tests
      publishRunAttachments: true

  - script: $(Build.Repository.LocalPath)\Scripts\CI\CreateFTDrop.bat $(configuration) $(Build.ArtifactStagingDirectory)\Tests
    displayName: Create functional tests drop

  - task: PublishBuildArtifacts@1
    displayName: Publish functional tests drop
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)\Tests
      artifactName: "FunctionalTests_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))

  - script: $(Build.Repository.LocalPath)\Scripts\CI\CreateInstallerDrop.bat $(configuration) $(Build.ArtifactStagingDirectory)\Installers
    displayName: Create installers drop

  - task: PublishBuildArtifacts@1
    displayName: Publish installers drop
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)\Installers
      artifactName: "Installers_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))
