name: $(date:yy)$(DayOfYear)$(rev:.r)

trigger: none

pr:
- master
- milestones/*
- releases/*
- servicing/*

variables:
  majorAndMinorVersion: '0.4'
  revision: '$(Build.BuildNumber)'
  platform: 'x64'
  configuration: release

jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: templates/windows-build-and-unit-test.yml

  - job: macOS
    pool:
      name: 'Hosted macOS'
    steps:
    - template: templates/macos-build-and-unit-test.yml
