trigger:
  - master
  - releases/*

pr:
  - master
  - milestones/*
  - releases/*
  - servicing/*

variables:
  - group: apple-development
  - name: branchCounter
    value: $[counter(variables['Build.SourceBranch'], 0)]
  - name: configuration
    value: Release

jobs:
  - job: win_build
    displayName: Windows Build and Unit Test
    pool:
      vmImage: windows-2019
    steps:
      - powershell: Scripts/CI/Set-Version.ps1 -SourceBranchCounter $(branchCounter)
        displayName: "Compute product version"
      - template: templates/win/build-and-unit-test.yml
      - template: templates/win/pack.unsigned.yml

  - job: win_functionaltest
    displayName: Windows Functional Test
    timeoutInMinutes: 90
    variables:
      configuration: Release
    pool:
      vmImage: windows-2019
    dependsOn: win_build
    condition: succeeded()
    steps:
      - checkout: none
      - template: templates/win/functional-test.yml
        parameters:
          useWatchman: false
