name: $(date:yy)$(DayOfYear)$(rev:.r)

trigger:
  - master
  - releases/shipped

pr:
  - master
  - milestones/*
  - releases/*
  - servicing/*

variables:
  majorAndMinorVersion: '0.4'
  revision: '$(Build.BuildNumber)'
  platform: 'x64'

jobs:
  - job: Windows_Build_and_UnitTests
    variables:
      platformFriendlyName: Windows
    strategy:
      maxParallel: 2
      matrix:
        debug:
          configuration: Debug
        release:
          configuration: Release
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: templates/windows-build-and-unit-test.yml

  - job: macOS_Build_and_UnitTests
    variables:
      platformFriendlyName: macOS
    strategy:
      maxParallel: 2
      matrix:
        debug:
          configuration: Debug
        release:
          configuration: Release
    pool:
      name: 'Hosted macOS'
    steps:
    - template: templates/macos-build-and-unit-test.yml

  - job: macOS_FunctionalTests
    variables:
      platformFriendlyName: macOS
      configuration: Release
    timeoutInMinutes: 30
    pool:
      name: 'Hosted macOS'
    dependsOn: macOS_Build_and_UnitTests
    condition: succeeded()
    steps:
      - checkout: none # Use the drop from macOS_Build_and_UnitTests job
      - template: templates/macos-functional-test.yml

  - job: Windows_FunctionalTests
    timeoutInMinutes: 30
    variables:
      platformFriendlyName: Windows
      configuration: Release
    pool:
      vmImage: vs2017-win2016
    dependsOn: Windows_Build_and_UnitTests
    condition: succeeded()
    steps:
    - checkout: none # We'll get the build drop from Windows_Build_and_UnitTests job
    - template: templates/windows-functional-test.yml
